"""
Demonstration of SalesAnalytics with PySpark.

This script shows how to use the SalesAnalytics class to analyze
the e-commerce data generated by main.py using PySpark.
"""

import logging
import sys
from pathlib import Path
from datetime import datetime

# Add src to path
sys.path.insert(0, str(Path(__file__).parent))

from src.spark_analytics import SalesAnalytics


def setup_logging() -> None:
    """Configure logging for the analytics demo."""
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(name)s | %(levelname)s | %(message)s",
        handlers=[
            logging.StreamHandler(),
            logging.FileHandler("logs/analytics_demo.log"),
        ],
    )


def main() -> None:
    """Main analytics demonstration."""
    logger = logging.getLogger(__name__)
    
    # Ensure logs directory exists
    Path("logs").mkdir(exist_ok=True)
    
    logger.info("=" * 80)
    logger.info("E-Commerce Sales Analytics Demo - PySpark")
    logger.info("=" * 80)
    
    start_time = datetime.now()
    
    try:
        # Initialize SalesAnalytics with context manager
        with SalesAnalytics(app_name="EcommerceSalesAnalytics") as analytics:
            
            logger.info("\n📊 Loading data from Parquet files...")
            # Load the generated data
            customers_df = analytics.load_parquet("data/raw/customers.parquet")
            products_df = analytics.load_parquet("data/raw/products.parquet")
            orders_df = analytics.load_parquet("data/raw/orders.parquet")
            
            # Get Spark config info
            logger.info("\n⚙️  Spark Configuration:")
            config = analytics.get_spark_config()
            key_configs = [
                "spark.executor.memory",
                "spark.driver.memory",
                "spark.serializer",
                "spark.sql.adaptive.enabled",
                "spark.master",
            ]
            for key in key_configs:
                if key in config:
                    logger.info(f"  {key}: {config[key]}")
            
            # 1. Top Customers by Revenue
            logger.info("\n💰 TOP 10 CUSTOMERS BY REVENUE")
            logger.info("-" * 80)
            top_customers = analytics.top_customers_by_revenue(
                orders_df, products_df, n=10
            )
            top_customers.show(10, truncate=False)
            logger.info(f"✓ Top customers analysis complete")
            
            # 2. Sales by Category
            logger.info("\n🏷️  SALES BY CATEGORY")
            logger.info("-" * 80)
            category_sales = analytics.sales_by_category(orders_df, products_df)
            category_sales.show(truncate=False)
            logger.info(f"✓ Category sales analysis complete")
            
            # 3. Monthly Trends
            logger.info("\n📈 MONTHLY REVENUE TRENDS")
            logger.info("-" * 80)
            monthly = analytics.monthly_trends(orders_df, products_df)
            monthly.show(20, truncate=False)
            logger.info(f"✓ Monthly trends analysis complete")
            
            # Calculate total revenue for summary
            logger.info("\n📊 SUMMARY STATISTICS")
            logger.info("-" * 80)
            total_revenue = category_sales.agg({"total_revenue": "sum"}).collect()[0][0]
            total_orders = orders_df.count()
            total_customers = customers_df.count()
            total_products = products_df.count()
            
            logger.info(f"  Total Customers: {total_customers:,}")
            logger.info(f"  Total Products: {total_products:,}")
            logger.info(f"  Total Orders: {total_orders:,}")
            logger.info(f"  Total Revenue: ${total_revenue:,.2f}")
            logger.info(f"  Avg Revenue per Order: ${total_revenue/total_orders:,.2f}")
            
    except FileNotFoundError as e:
        logger.error(f"❌ Data files not found: {e}")
        logger.error("Please run 'python main.py' first to generate the Parquet files")
        sys.exit(1)
    except Exception as e:
        logger.error(f"❌ Error during analytics: {e}", exc_info=True)
        sys.exit(1)
    finally:
        end_time = datetime.now()
        elapsed = (end_time - start_time).total_seconds()
        logger.info("\n" + "=" * 80)
        logger.info(f"Analytics completed in {elapsed:.2f} seconds")
        logger.info("=" * 80 + "\n")


if __name__ == "__main__":
    setup_logging()
    main()
