"""
Run PySpark Analytics on E-Commerce Data

This script demonstrates the SalesAnalytics class by:
1. Loading Parquet files generated by main.py
2. Running all three analytics methods
3. Displaying results with timing information
"""

import sys
import logging
from pathlib import Path
from datetime import datetime
from time import time

# Add src to path
sys.path.insert(0, str(Path(__file__).parent))

from src.spark_analytics import SalesAnalytics


def setup_logging() -> None:
    """Configure logging for the script."""
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)s | %(message)s",
        handlers=[
            logging.StreamHandler(),
        ],
    )


def print_section(title: str) -> None:
    """Print a formatted section header."""
    print("\n" + "=" * 80)
    print(f"  {title}")
    print("=" * 80 + "\n")


def main() -> None:
    """Main execution of analytics pipeline."""
    logger = logging.getLogger(__name__)
    
    print_section("E-COMMERCE SALES ANALYTICS")
    
    overall_start = time()
    
    try:
        # Initialize SalesAnalytics
        print("🚀 Initializing Spark session...")
        init_start = time()
        analytics = SalesAnalytics(app_name="RunAnalytics")
        init_time = time() - init_start
        print(f"   ✓ Initialization completed in {init_time:.2f}s\n")
        
        # Load data
        print("📂 Loading Parquet files from data/raw/...")
        load_start = time()
        
        print("   → Loading customers.parquet...")
        customers_df = analytics.load_parquet("data/raw/customers.parquet")
        
        print("   → Loading products.parquet...")
        products_df = analytics.load_parquet("data/raw/products.parquet")
        
        print("   → Loading orders.parquet...")
        orders_df = analytics.load_parquet("data/raw/orders.parquet")
        
        load_time = time() - load_start
        print(f"   ✓ Data loading completed in {load_time:.2f}s\n")
        
        # Analytics 1: Top Customers by Revenue
        print_section("1️⃣  TOP CUSTOMERS BY REVENUE")
        print("Calculating top 10 customers by total revenue spent...\n")
        
        top_customers_start = time()
        top_customers = analytics.top_customers_by_revenue(orders_df, products_df, n=10)
        top_customers_time = time() - top_customers_start
        
        top_customers.show(10, truncate=False)
        print(f"\n⏱️  Execution time: {top_customers_time:.2f}s")
        
        # Analytics 2: Sales by Category
        print_section("2️⃣  SALES BY CATEGORY")
        print("Aggregating sales metrics by product category...\n")
        
        category_start = time()
        category_sales = analytics.sales_by_category(orders_df, products_df)
        category_time = time() - category_start
        
        category_sales.show(truncate=False)
        print(f"\n⏱️  Execution time: {category_time:.2f}s")
        
        # Analytics 3: Monthly Trends
        print_section("3️⃣  MONTHLY REVENUE TRENDS")
        print("Calculating month-over-month revenue growth with Window functions...\n")
        
        trends_start = time()
        monthly_trends = analytics.monthly_trends(orders_df, products_df)
        trends_time = time() - trends_start
        
        monthly_trends.show(20, truncate=False)
        print(f"\n⏱️  Execution time: {trends_time:.2f}s")
        
        # Summary
        print_section("EXECUTION SUMMARY")
        print(f"Initialization:      {init_time:>8.2f}s")
        print(f"Data Loading:        {load_time:>8.2f}s")
        print(f"Top Customers:       {top_customers_time:>8.2f}s")
        print(f"Category Sales:      {category_time:>8.2f}s")
        print(f"Monthly Trends:      {trends_time:>8.2f}s")
        print("-" * 35)
        
        total_analytics_time = top_customers_time + category_time + trends_time
        overall_time = time() - overall_start
        
        print(f"Total Analytics:     {total_analytics_time:>8.2f}s")
        print(f"Total Time:          {overall_time:>8.2f}s")
        
        # Cleanup
        print("\n🛑 Stopping Spark session...")
        analytics.stop()
        print("   ✓ Spark session stopped\n")
        
        print_section("ANALYTICS COMPLETE ✅")
        
    except FileNotFoundError as e:
        print(f"\n❌ Error: {e}")
        print("\nPlease ensure data files exist:")
        print("  - data/raw/customers.parquet")
        print("  - data/raw/products.parquet")
        print("  - data/raw/orders.parquet")
        print("\nGenerate them by running: python main.py")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Error: {e}")
        logger.exception("Analytics execution failed")
        sys.exit(1)


if __name__ == "__main__":
    setup_logging()
    main()
